# Generated by Django 4.2.5 on 2023-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('for_sale', models.BooleanField()),
                ('room_number', models.PositiveIntegerField()),
                ('year_built', models.PositiveIntegerField()),
                ('square_meter', models.PositiveIntegerField()),
            ],
        ),
    ]
